#!/bin/bash
#
# chkconfig: 2345 80 20
# run on level 2345

# Source function library.
. /etc/init.d/functions

VIREOUSER=thesiscentralsu
VIREOHOME=/home/$VIREOUSER/Vireo

sudo -u $VIREOUSER $VIREOHOME/play.sh $1  2>&1 > /dev/null
exit $?

