#!/bin/tcsh 
set dept = $1 
cd `dirname $0`
pwd 
set echo 
/bin/cp AdditionalPrograms.xlsx RestrictionsFinalWithId.xlsx $dep 
python ../enhanceAips.py --thesis $dept/*.xlsx -r $dpet/RestrictionsFinalWithId.xlsx --add_certs $dept/AdditionalPrograms.xlsx --aips $dept/DSpaceSimpleArchive -l INFO  > $dept/$dept-list.tsv
python ../sortByStatus.py  --thesis $dept/*.xlsx --aips $dept/DSpaceSimpleArchive 

